apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: laravel-k8s
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: laravel-k8s
    tier: frontend
